/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Aug 11 16:05:30 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.govmade.entity.system.organization;

import java.io.Serializable;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.type.Alias;

import com.govmade.entity.base.IdBaseEntity;

/** 
* @ClassName: Company 
* @Description: TODO(机构) 
* @author Dongjie 154046519@qq.com 
* @date 2016年12月6日 上午10:41
*  
*/
@Alias("Company")
public class Company extends IdBaseEntity{

	private String companyNumber;//单位编号
	private String companyName;//单位名称
	private String companyCode;//机构代码
	private String address;//地址
	private Integer cityId;//所属城市
	private String lng;//经度
	private String lat;//纬度
	public String getCompanyNumber() {
		return companyNumber;
	}
	public void setCompanyNumber(String companyNumber) {
		this.companyNumber = companyNumber;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getCompanyCode() {
		return companyCode;
	}
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public Integer getCityId() {
		return cityId;
	}
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}
	public String getLng() {
		return lng;
	}
	public void setLng(String lng) {
		this.lng = lng;
	}
	public String getLat() {
		return lat;
	}
	public void setLat(String lat) {
		this.lat = lat;
	}
	

}
