/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Aug 11 16:05:30 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.govmade.entity.system.organization;

import java.io.Serializable;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.type.Alias;

import com.govmade.entity.base.IdBaseEntity;

/** 
* @ClassName: Groups 
* @Description: TODO(机构部门) 
* @author Dongjie 154046519@qq.com 
* @date 2016年12月6日 16:08
*  
*/
@Alias("Groups")
public class Groups extends IdBaseEntity{
	private String name;//部门名称
	private String number;//编号
	private Integer companyId;//单位ID
	private String contract;//联系人
	private String telephone;//联系电话
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getNumber() {
		return number;
	}
	public void setNumber(String number) {
		this.number = number;
	}
	public Integer getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	public String getContract() {
		return contract;
	}
	public void setContract(String contract) {
		this.contract = contract;
	}
	public String getTelephone() {
		return telephone;
	}
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	
}
