/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Aug 11 16:05:30 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.govmade.entity.system.rbac;

import java.io.Serializable;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.type.Alias;

import com.govmade.entity.base.IdBaseEntity;

/** 
* @ClassName: RolePermission 
* @Description: TODO(角色和权限的关联表) 
* @author Dongjie 154046519@qq.com 
* @date 2016年11月2日 下午1:39:10 
*  
*/
@Alias("RolePermission")
public class RolePermission extends IdBaseEntity {
	
	private static final long serialVersionUID = 3607428254210782378L;
	
	private Integer roleId;
	
	private Integer permissionId;

	private Integer scopeId;

	private String validity;

	private Permission permission;
	
	public String getValidity() {
		return validity;
	}

	public void setValidity(String validity) {
		this.validity = validity;
	}

	public Integer getPermissionId() {
		return permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	public Integer getScopeId() {
		return scopeId;
	}

	public void setScopeId(Integer scopeId) {
		this.scopeId = scopeId;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Permission getPermission() {
		return permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	
}
