/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Aug 11 16:05:30 CST 2006 by MyEclipse Hibernate Tool.
 */
package com.govmade.entity.system.rbac;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

import com.govmade.common.utils.StringUtil;
import com.govmade.entity.base.IdBaseEntity;

/** 
* @ClassName: Scope 
* @Description: TODO(数据规则) 
* @author Dongjie 154046519@qq.com 
* @date 2016年11月2日 下午1:38:48 
*  
*/
@Alias("Scope")
public class Scope extends IdBaseEntity implements Cloneable{


	private static final long serialVersionUID = 7746198201315972601L;

	private String name; 

	private String note;

	private String permissions;
	
	private String value;

	private Integer isChecked;
	
	public Integer getIsChecked() {
		return isChecked;
	}

	public void setIsChecked(Integer isChecked) {
		this.isChecked = isChecked;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}


	public String getPermissions() {
		return  permissions;
	}

	public void setPermissions(String permissions) {
		this.permissions = StringUtil.toSQLStr(permissions);
	}

	public Integer getIsSelected() {
		return isChecked;
	}

	public void setIsSelected(Integer isSelected) {
		this.isChecked = isSelected;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}




}
